#普通数据的配置
name: zhangsan

#对象的配置
person:
  name: zhangsan
  age: 18
  addr: beijing

#行内对象配置(用得少)
#person: {name: zhangsan,age: 18,addr: beijing}


#server:
#  port: 8080

#配置数组、集合(普通字符串)
city:
  - beijing
  - shanghai
  - guangzhou

#city: [beijing,tianjin,shanghai,guangzhou]

#配置数组、集合(对象数据)

student:
  - name: tom
    age: 18
    addr: beijing
  - name: xiaoming
    age: 20
    addr: shanghai

#student: [{name: xiaoming,age: 20,addr: shanghai},{name: tom,age: 18,addr: beijing}]

#Map配置
map:
  key1: value1
  key2: value2

